// Centralised service catalogue. Each entry powers the listing cards and the
// dedicated /services/[slug] detail page.

export const CATEGORIES = {
  "web-development": {
    slug: "web-development",
    title: "Web Development Services",
    tagline:
      "Custom websites, web applications, and operational systems engineered for scale.",
    description:
      "From marketing sites that convert to enterprise-grade platforms that run your business, we design and engineer web products that move metrics — not just pixels.",
    image: "/web-development.png",
    accent: "from-brand-600 to-brand-400",
  },
  "ai-automation": {
    slug: "ai-automation",
    title: "AI & Automation Services",
    tagline:
      "AI agents, intelligent automations, and data products that compound productivity.",
    description:
      "We embed AI into the workflows that actually run your business — sales, support, operations, and analytics — so your team ships more with less effort.",
    image: "/ai-automation.png",
    accent: "from-accent-500 to-brand-500",
  },
};

export const SERVICES = [
  // ───────────── WEB DEVELOPMENT ─────────────
  {
    slug: "business-website",
    category: "web-development",
    title: "Business Website",
    subtitle: "Corporate & Brochure Sites",
    tagline: "A polished digital storefront that earns trust on first scroll.",
    description:
      "Professional corporate websites that communicate authority, articulate your value, and convert qualified visitors into pipeline.",
    image: "/web-development-images/business-website.png",
    icon: "Briefcase",
    overview:
      "Your website is the first handshake with every prospect. We build corporate websites that load fast, rank well, and tell a coherent brand story — engineered with modern frameworks, CMS-driven content, and conversion-optimised layouts so your marketing team can ship updates without engineering tickets.",
    features: [
      { title: "Conversion-first architecture", description: "Information design tuned around the buyer journey, with clear CTAs on every section." },
      { title: "Headless CMS", description: "Edit content with Sanity, Contentful, or Strapi — preview, schedule, and roll back changes safely." },
      { title: "Core Web Vitals tuned", description: "Sub-second LCP, image optimisation, and edge caching out of the box." },
      { title: "Multilingual & multi-region", description: "i18n routing, locale switching, and region-specific assets for global teams." },
      { title: "Built-in SEO", description: "Schema markup, sitemap, OG tags, and analytics wired from day one." },
      { title: "Brand-system ready", description: "Design tokens, reusable sections, and Figma-to-code parity." },
    ],
    benefits: [
      "Higher organic visibility from technical SEO foundations",
      "Faster content velocity for your marketing team",
      "Reduced bounce rate from page-speed optimisation",
      "Consistent brand presentation across regions",
    ],
    useCases: [
      "B2B SaaS marketing site",
      "Enterprise corporate presence",
      "Professional services firm (legal, consulting, financial)",
      "Manufacturing & industrial brand site",
    ],
    techStack: ["Next.js", "Tailwind CSS", "Sanity / Contentful", "Vercel", "TypeScript", "Framer Motion"],
    process: [
      { step: "Discovery", description: "Stakeholder interviews, audience research, sitemap and content audit." },
      { step: "Design", description: "Figma wireframes, brand-aligned high-fidelity mockups, prototype review." },
      { step: "Build", description: "Component-based development, CMS modelling, accessibility checks." },
      { step: "Launch & Optimise", description: "Migration, performance tuning, analytics setup, ongoing A/B testing." },
    ],
    timeline: "4 – 8 weeks",
    deliverables: ["Responsive multi-page website", "Headless CMS setup", "Analytics & SEO baseline", "Editor training & handover"],
  },
  {
    slug: "landing-page",
    category: "web-development",
    title: "Landing Page & Lead Generation",
    subtitle: "Campaign sites that convert",
    tagline: "Purpose-built pages engineered around a single conversion goal.",
    description:
      "High-converting landing pages for paid campaigns, product launches, and lead-gen funnels — instrumented end-to-end.",
    image: "/web-development-images/landing-page.png",
    icon: "Rocket",
    overview:
      "When every click costs money, your landing page has to earn it back. We design and build campaign pages around a single conversion goal — gated content, demo requests, free trials — with crisp messaging hierarchy, social proof, and a frictionless form flow.",
    features: [
      { title: "Single-conversion design", description: "Every block on the page works toward one CTA — measured, not decorative." },
      { title: "A/B testing ready", description: "Variant infrastructure for headlines, hero media, CTAs, and form fields." },
      { title: "Form intelligence", description: "Validation, multi-step UX, progressive profiling, and CRM sync." },
      { title: "Heatmap & event tracking", description: "Hotjar, GA4, and ad-platform pixels pre-wired." },
      { title: "Sub-1.5s load", description: "Critical-CSS, image preload, edge-rendered hero." },
    ],
    benefits: [
      "Lower cost-per-lead from improved landing-page conversion rate",
      "Faster iteration loop with built-in A/B framework",
      "Higher quality leads via progressive form profiling",
      "Cleaner attribution with full event tracking",
    ],
    useCases: [
      "Paid search & social campaign destinations",
      "Webinar & event registration pages",
      "Free trial / demo request funnels",
      "Whitepaper and gated-content downloads",
    ],
    techStack: ["Next.js", "Tailwind CSS", "HubSpot / Salesforce / Pipedrive", "GA4", "Hotjar", "Vercel"],
    process: [
      { step: "Strategy", description: "Define ICP, value props, objections, and success metric." },
      { step: "Copy & Design", description: "Conversion copy, hierarchy, motion, and proof assets." },
      { step: "Build & Integrate", description: "CRM, marketing automation, tracking, and consent." },
      { step: "Test & Iterate", description: "Run experiments, monitor heatmaps, refine over time." },
    ],
    timeline: "2 – 4 weeks",
    deliverables: ["Optimised landing page", "Form + CRM integration", "Event & pixel tracking", "First A/B test setup"],
  },
  {
    slug: "ecommerce-store",
    category: "web-development",
    title: "eCommerce Store",
    subtitle: "Online retail platforms",
    tagline: "Storefronts engineered for conversion, speed, and global scale.",
    description:
      "Full-funnel eCommerce builds on Shopify, Medusa, or custom stacks — fast, beautiful, and built to grow.",
    image: "/web-development-images/ecommerce-store.png",
    icon: "ShoppingBag",
    overview:
      "We build eCommerce experiences that feel like premium product apps — fast PDPs, smart search, instant cart, and checkout flows tuned for mobile. Platform-agnostic: Shopify Hydrogen for speed-to-market, Medusa or custom for unique logic.",
    features: [
      { title: "Headless storefront", description: "Decoupled commerce engine with a custom-designed front end." },
      { title: "Smart search & filtering", description: "Algolia or Meilisearch with merchandising, synonyms, and personalisation." },
      { title: "One-page checkout", description: "Wallet payments, address auto-complete, abandoned cart recovery." },
      { title: "Subscriptions & bundles", description: "Recurring orders, build-your-bundle, gifting flows." },
      { title: "Multi-currency / multi-region", description: "Geo-routing, local payment methods, tax compliance." },
      { title: "ERP & 3PL sync", description: "Real-time inventory, fulfilment, and order status." },
    ],
    benefits: [
      "Higher conversion rate from sub-second product pages",
      "Larger AOV via personalised recommendations and bundles",
      "Lower abandonment with frictionless checkout",
      "Global readiness for currency, tax, and shipping",
    ],
    useCases: [
      "DTC consumer brands",
      "Premium fashion & lifestyle",
      "Specialty food & beverage",
      "Health, wellness & beauty",
    ],
    techStack: ["Shopify / Medusa", "Next.js Commerce", "Algolia", "Stripe / Adyen", "Klaviyo", "Vercel"],
    process: [
      { step: "Strategy", description: "Catalogue audit, journey mapping, conversion benchmarks." },
      { step: "Design", description: "PDP, PLP, cart, and checkout designed for mobile-first." },
      { step: "Build", description: "Headless integration, search, payments, and analytics." },
      { step: "Launch", description: "Migration, SEO redirects, performance pass, post-launch CRO." },
    ],
    timeline: "8 – 14 weeks",
    deliverables: ["Headless storefront", "Search & merchandising", "Payments & checkout", "Analytics & CRO setup"],
  },
  {
    slug: "digital-products-store",
    category: "web-development",
    title: "Digital Products Store",
    subtitle: "Sell downloads, licenses & access",
    tagline: "A complete storefront for digital goods — instant delivery, licensing, and entitlements.",
    description:
      "Marketplaces and stores for templates, courses, plugins, software licenses, and downloadable assets.",
    image:
      "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=1600&q=80&auto=format&fit=crop",
    icon: "Download",
    overview:
      "Digital goods have unique requirements: instant delivery, license keys, version updates, and piracy protection. We build storefronts that handle entitlements gracefully — buyers get what they need immediately, and you get clean recurring revenue.",
    features: [
      { title: "Instant delivery", description: "Secure download links, license keys, and access provisioning at checkout." },
      { title: "Version management", description: "Push updates, changelogs, and notifications to existing buyers." },
      { title: "Author / vendor accounts", description: "Multi-seller marketplaces with payout splits." },
      { title: "DRM & watermarking", description: "Anti-piracy measures for media and document downloads." },
      { title: "Bundle & subscription support", description: "Tiered access, season passes, and lifetime deals." },
    ],
    benefits: [
      "Zero fulfilment overhead",
      "Higher LTV through subscriptions and updates",
      "Marketplace network effects when you onboard vendors",
      "Protection against unauthorised distribution",
    ],
    useCases: [
      "Template, theme, and plugin marketplaces",
      "Online course platforms (mini-LMS)",
      "Stock asset libraries (audio, video, 3D)",
      "Software license sales",
    ],
    techStack: ["Next.js", "Stripe Billing", "AWS S3 / CloudFront", "Supabase / PostgreSQL", "License keys (Keygen / custom)"],
    process: [
      { step: "Scope", description: "Define product types, entitlements, and licensing rules." },
      { step: "Architecture", description: "Storage, delivery, payments, and access control." },
      { step: "Build", description: "Storefront, dashboard, vendor portal, anti-fraud." },
      { step: "Launch", description: "Migration, payout setup, SEO, and ongoing support." },
    ],
    timeline: "6 – 12 weeks",
    deliverables: ["Storefront + checkout", "Author dashboard", "License/entitlement engine", "Update notification system"],
  },
  {
    slug: "b2b-ecommerce",
    category: "web-development",
    title: "B2B eCommerce & Online Ordering",
    subtitle: "Wholesale & dealer portals",
    tagline: "Wholesale ordering portals with tiered pricing, account-level catalogues, and ERP sync.",
    description:
      "Self-service ordering platforms for distributors, dealers, and corporate buyers — built for repeat, high-volume purchasing.",
    image:
      "https://images.unsplash.com/photo-1553413077-190dd305871c?w=1600&q=80&auto=format&fit=crop",
    icon: "Warehouse",
    overview:
      "B2B buyers don't shop — they re-order. We build portals around account-level pricing, contract catalogues, credit limits, and PO workflows, with deep ERP integration so your sales reps stop being order takers and start being trusted advisors.",
    features: [
      { title: "Account-based pricing", description: "Customer-specific price lists, volume tiers, and contract pricing." },
      { title: "Quick-order & reorder", description: "Bulk SKU entry, CSV upload, last-order reorder in one click." },
      { title: "Quote & PO workflow", description: "Request-for-quote, approval routing, and PO-based checkout." },
      { title: "Credit & terms", description: "Net-30/60 invoicing, credit limits, statement views." },
      { title: "ERP & EDI integration", description: "Real-time inventory, pricing, and order sync with SAP, NetSuite, Dynamics, Odoo." },
      { title: "Sales-rep co-pilot", description: "Place orders on behalf of accounts, view pipeline, share quotes." },
    ],
    benefits: [
      "Lower cost-to-serve by automating routine reorders",
      "Higher rep productivity with shared quote/order tools",
      "Faster order cycle times via PO workflows",
      "Real-time visibility for both buyer and seller",
    ],
    useCases: [
      "Distributor / wholesaler ordering portals",
      "Manufacturer dealer networks",
      "Foodservice & hospitality supply",
      "Industrial parts & MRO",
    ],
    techStack: ["Next.js", "Medusa / Custom", "SAP / NetSuite / Dynamics", "Stripe / Mollie", "PostgreSQL", "Twilio"],
    process: [
      { step: "Discovery", description: "Map account hierarchies, pricing rules, and approval flows." },
      { step: "Integration design", description: "ERP / EDI fields, sync cadence, error handling." },
      { step: "Build", description: "Portal, admin, rep tools, and observability." },
      { step: "Rollout", description: "Pilot accounts, training, and phased migration." },
    ],
    timeline: "12 – 20 weeks",
    deliverables: ["B2B portal", "ERP integration", "Rep dashboard", "Reporting & analytics"],
  },
  {
    slug: "client-portal",
    category: "web-development",
    title: "Custom Client Portal & Self-Service Dashboard",
    subtitle: "Branded customer experiences",
    tagline: "Branded portals where your clients view, manage, and interact with their accounts.",
    description:
      "Self-service dashboards for project status, file sharing, billing, support, and account management.",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&q=80&auto=format&fit=crop",
    icon: "LayoutDashboard",
    overview:
      "Email threads don't scale. A client portal centralises everything your customers need — projects, deliverables, invoices, support — under your brand. Result: fewer status calls, faster turnaround, and a much more premium feel.",
    features: [
      { title: "Role-based access", description: "Granular permissions per client, team, and external collaborator." },
      { title: "Project & deliverable views", description: "Timelines, files, approvals, and threaded comments." },
      { title: "Billing & invoices", description: "Payment history, downloadable invoices, online payment." },
      { title: "Support inbox", description: "Built-in ticketing or integration with Zendesk, Intercom, Freshdesk." },
      { title: "SSO & 2FA", description: "Enterprise-grade auth with Google, Microsoft, Okta, SAML." },
      { title: "White-label theming", description: "Your logo, colours, and domain — your clients never see ours." },
    ],
    benefits: [
      "Fewer support touches per project",
      "Stronger client perception of professionalism",
      "Faster approval cycles with in-portal sign-off",
      "Reduced email & file-version chaos",
    ],
    useCases: [
      "Agencies & consultancies",
      "Legal & accounting practices",
      "Construction & architecture firms",
      "Healthcare practitioner portals",
    ],
    techStack: ["Next.js", "Supabase / Auth0", "PostgreSQL", "Stripe", "AWS S3", "SendGrid"],
    process: [
      { step: "Workflow mapping", description: "Identify the touchpoints replacing email & spreadsheets." },
      { step: "UX design", description: "Portal IA, role views, mobile-friendly layouts." },
      { step: "Build", description: "Auth, modules, integrations, and notifications." },
      { step: "Onboard clients", description: "Migration, training, and gradual feature rollout." },
    ],
    timeline: "8 – 16 weeks",
    deliverables: ["Branded portal", "Auth & roles", "Module set (projects, billing, support)", "Admin console"],
  },
  {
    slug: "booking-system",
    category: "web-development",
    title: "Booking & Appointment System",
    subtitle: "Scheduling that pays for itself",
    tagline: "Online scheduling for services, classes, resources, and multi-location operations.",
    description:
      "Custom booking platforms with calendar sync, payments, reminders, and capacity management.",
    image:
      "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=1600&q=80&auto=format&fit=crop",
    icon: "Calendar",
    overview:
      "Generic booking SaaS gets you 80% there — and then breaks on the 20% that actually defines your business. We build booking systems around your real rules: resource constraints, buffer times, dynamic pricing, multi-location, group bookings, and your tone of voice.",
    features: [
      { title: "Smart availability engine", description: "Buffer times, blackout dates, multi-resource constraints, time-zone aware." },
      { title: "Multi-location & multi-service", description: "Locations, staff, equipment, rooms — bookable independently or as bundles." },
      { title: "Payments & deposits", description: "Full payment, deposits, packages, and gift cards." },
      { title: "Automated reminders", description: "Email + SMS at customer-defined intervals to cut no-shows." },
      { title: "Calendar sync", description: "Two-way sync with Google, Outlook, iCal." },
      { title: "Customer accounts", description: "Booking history, easy rebooking, loyalty points." },
    ],
    benefits: [
      "30 – 60% reduction in no-shows from reminders",
      "Higher utilisation from smart availability",
      "Lower admin load — no more phone-tag scheduling",
      "Customer self-service available 24/7",
    ],
    useCases: [
      "Health & wellness clinics",
      "Salons, spas, and beauty studios",
      "Fitness studios & classes",
      "Equipment rental & coworking spaces",
    ],
    techStack: ["Next.js", "PostgreSQL", "Stripe", "Twilio / SendGrid", "Google Calendar API", "Redis"],
    process: [
      { step: "Mapping", description: "Resources, services, rules, edge cases." },
      { step: "UX", description: "Customer flow, admin flow, mobile-first." },
      { step: "Build", description: "Availability engine, payments, notifications." },
      { step: "Launch", description: "Migration, staff training, and continuous tuning." },
    ],
    timeline: "6 – 12 weeks",
    deliverables: ["Customer booking site", "Staff/admin console", "Reminder + payment automation", "Reporting"],
  },
  {
    slug: "invoice-billing",
    category: "web-development",
    title: "Invoice & Billing System",
    subtitle: "Get paid faster, automatically",
    tagline: "Recurring billing, invoicing, and dunning that runs without you.",
    description:
      "Invoicing platforms with subscriptions, usage billing, multi-currency, tax compliance, and automated reminders.",
    image:
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1600&q=80&auto=format&fit=crop",
    icon: "Receipt",
    overview:
      "Billing shouldn't be where your revenue leaks. We build invoicing systems that handle one-off, subscription, and usage-based pricing — with multi-currency, tax rules, dunning, and finance-team-grade reporting.",
    features: [
      { title: "Subscriptions & usage billing", description: "Tiers, seats, metered usage, mid-cycle changes with proration." },
      { title: "Multi-currency & tax", description: "Localised currencies, VAT/GST/sales-tax, e-invoicing where required." },
      { title: "Automated dunning", description: "Smart retries, customer notifications, and escalation rules." },
      { title: "Branded invoices & portal", description: "Customers view, download, and pay invoices on your domain." },
      { title: "Accounting sync", description: "QuickBooks, Xero, NetSuite, and SAP integration." },
      { title: "Audit trail", description: "Full event log for finance and compliance teams." },
    ],
    benefits: [
      "Lower involuntary churn with smart retries",
      "Faster cash collection from automated reminders",
      "Cleaner books with native accounting sync",
      "Less manual finance work, more strategic time",
    ],
    useCases: [
      "SaaS & subscription products",
      "Professional services firms",
      "Membership organisations",
      "Usage-billed APIs & infrastructure",
    ],
    techStack: ["Next.js", "Stripe Billing / Paddle", "QuickBooks / Xero / NetSuite", "PostgreSQL", "PDF generation", "S3"],
    process: [
      { step: "Pricing model", description: "Map plans, usage, taxes, and edge cases." },
      { step: "System design", description: "Billing engine, dunning, and accounting flows." },
      { step: "Build & integrate", description: "Customer portal, ops dashboard, sync." },
      { step: "Migrate & launch", description: "Backfill data, parallel run, cutover." },
    ],
    timeline: "8 – 14 weeks",
    deliverables: ["Billing engine", "Customer portal", "Accounting integration", "Finance dashboard"],
  },
  {
    slug: "inventory-management",
    category: "web-development",
    title: "Inventory & Stock Management",
    subtitle: "Real-time stock control",
    tagline: "One source of truth for stock — across warehouses, channels, and teams.",
    description:
      "Multi-warehouse inventory platforms with barcoding, batches, lot tracking, and sales-channel sync.",
    image:
      "https://images.unsplash.com/photo-1553413077-190dd305871c?w=1600&q=80&auto=format&fit=crop",
    icon: "Boxes",
    overview:
      "When stock numbers don't match reality, every downstream system breaks. We build inventory platforms that act as the operational truth — bringing receiving, transfers, picks, counts, and channel sync under one accurate, real-time ledger.",
    features: [
      { title: "Multi-warehouse & bin", description: "Locations, zones, bins, and aisle pathing." },
      { title: "Barcode & label printing", description: "Mobile scanners, Zebra-compatible label flows, GS1 barcodes." },
      { title: "Batch & lot tracking", description: "Expiry, serial numbers, recalls, and full traceability." },
      { title: "Channel sync", description: "Two-way sync with Shopify, Amazon, eBay, marketplaces." },
      { title: "Cycle counting", description: "ABC analysis, scheduled counts, variance reporting." },
      { title: "Demand alerts", description: "Reorder points, safety stock, and supplier purchase orders." },
    ],
    benefits: [
      "Fewer oversells and stockouts",
      "Faster picks with bin-level locations",
      "Tighter cash via reduced safety stock",
      "Audit-ready batch and lot history",
    ],
    useCases: [
      "Multi-warehouse DTC brands",
      "3PL fulfilment operations",
      "Food & beverage with expiry tracking",
      "Industrial parts & MRO",
    ],
    techStack: ["Next.js", "PostgreSQL", "React Native (scanner app)", "Zebra label printers", "Webhooks / EDI", "Redis"],
    process: [
      { step: "Audit", description: "Map locations, SKUs, channels, and pain points." },
      { step: "Design", description: "Data model, scanner UX, label flows." },
      { step: "Build", description: "Core platform, scanner app, integrations." },
      { step: "Roll out", description: "Warehouse pilot, training, full deployment." },
    ],
    timeline: "12 – 20 weeks",
    deliverables: ["Web admin", "Mobile scanner app", "Channel integrations", "Reporting"],
  },
  {
    slug: "pos-system",
    category: "web-development",
    title: "Point of Sale (POS) System",
    subtitle: "Modern in-store + online unified retail",
    tagline: "Lightning-fast POS that unifies in-store, online, and back office.",
    description:
      "Touchscreen POS apps with offline mode, payments, returns, and full integration with eCommerce and inventory.",
    image:
      "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=1600&q=80&auto=format&fit=crop",
    icon: "ScanLine",
    overview:
      "Unified commerce means your in-store till sees the same inventory, customers, and promotions as your website. We build POS that works offline, runs on iPads or Android, and feels as fast as a native app — so cashiers love it and customers don't wait.",
    features: [
      { title: "Offline-first", description: "Local-first architecture syncs when network returns — never lose a sale." },
      { title: "Payments integrated", description: "Card-present, contactless, wallets, split tender, and tipping." },
      { title: "Customer recognition", description: "Loyalty lookup, purchase history, and personalised discounts at checkout." },
      { title: "Returns & exchanges", description: "Receipt scan, store credit, partial returns, and refund workflows." },
      { title: "Cash management", description: "Drawer counts, end-of-day reconciliation, multi-till support." },
      { title: "Unified inventory", description: "Real-time stock with web & marketplace channels." },
    ],
    benefits: [
      "Faster checkout, shorter queues",
      "Smarter upsells with customer history",
      "Tighter shrink controls with audit trails",
      "Single view of sales across channels",
    ],
    useCases: [
      "Apparel & lifestyle retail",
      "Coffee shops & QSR chains",
      "Boutique grocery & specialty food",
      "Salons, gyms, and service retail",
    ],
    techStack: ["React Native / Capacitor", "Next.js admin", "Stripe Terminal / Adyen", "PostgreSQL", "Redis", "Sync engine"],
    process: [
      { step: "Hardware & flows", description: "Choose terminals, printers, drawers, and define cashier flows." },
      { step: "Design", description: "Cashier UX, manager tools, reporting dashboards." },
      { step: "Build", description: "POS app, admin, payments, and offline sync." },
      { step: "Roll out", description: "Per-store pilot, training, performance tuning." },
    ],
    timeline: "12 – 20 weeks",
    deliverables: ["POS apps (tablet)", "Admin dashboard", "Payments + hardware", "Reporting"],
  },
  {
    slug: "order-delivery",
    category: "web-development",
    title: "Order & Delivery Management",
    subtitle: "End-to-end fulfilment ops",
    tagline: "Order routing, dispatch, and live-tracking platforms for delivery operations.",
    description:
      "Order orchestration with dispatch, routing, driver apps, and customer tracking.",
    image:
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1600&q=80&auto=format&fit=crop",
    icon: "Truck",
    overview:
      "Delivery operations live or die on routing, ETAs, and visibility. We build order-and-delivery platforms with smart dispatch, driver mobile apps, customer tracking links, and the back-office tools your dispatchers actually need.",
    features: [
      { title: "Smart dispatch", description: "Auto-assign by proximity, capacity, skill, or time window." },
      { title: "Route optimisation", description: "Multi-stop routes with traffic, time windows, and constraints." },
      { title: "Driver mobile app", description: "Manifest, navigation, proof-of-delivery, signatures, photos." },
      { title: "Live customer tracking", description: "Branded tracking page, SMS updates, dynamic ETAs." },
      { title: "Dispatcher console", description: "Live map, status board, manual reassignment, exception handling." },
      { title: "POS / OMS integration", description: "Hooks into your existing order pipeline." },
    ],
    benefits: [
      "Fewer missed deliveries and complaints",
      "More stops per driver per day",
      "Higher CSAT from live tracking",
      "Lower fuel costs from optimised routes",
    ],
    useCases: [
      "Restaurant & grocery delivery",
      "Local logistics & courier services",
      "Field service dispatch",
      "B2B distribution & last-mile",
    ],
    techStack: ["Next.js", "React Native (driver app)", "Mapbox / Google Maps", "PostgreSQL + PostGIS", "Twilio", "WebSockets"],
    process: [
      { step: "Process mapping", description: "Order intake, dispatch rules, exceptions." },
      { step: "App design", description: "Dispatcher console, driver UX, customer UI." },
      { step: "Build & integrate", description: "Engine, mobile apps, integrations." },
      { step: "Operationalise", description: "Pilot zones, driver training, ongoing tuning." },
    ],
    timeline: "12 – 20 weeks",
    deliverables: ["Dispatcher console", "Driver app", "Customer tracking", "OMS integration"],
  },
  {
    slug: "hr-management",
    category: "web-development",
    title: "HR & Employee Management",
    subtitle: "Lifecycle from onboarding to offboarding",
    tagline: "A people platform that scales — directory, leave, performance, and payroll-ready.",
    description:
      "Custom HR systems covering employee directory, leave, performance, documents, and integrations.",
    image:
      "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1600&q=80&auto=format&fit=crop",
    icon: "Users",
    overview:
      "Off-the-shelf HRIS rarely fits how your company actually runs. We build custom HR platforms that mould around your org structure, leave policies, performance cadence, and compliance needs — with clean integrations into payroll and identity providers.",
    features: [
      { title: "Employee directory & org chart", description: "Hierarchies, reporting lines, and team profiles." },
      { title: "Leave & time-off", description: "Policy engine, accruals, approvals, calendars, holidays per region." },
      { title: "Performance reviews", description: "OKRs, goals, 360s, and cycle automation." },
      { title: "Documents & e-sign", description: "Contracts, policies, expiry tracking, e-signature integration." },
      { title: "Onboarding & offboarding", description: "Checklists, IT provisioning, asset tracking." },
      { title: "Payroll & IdP sync", description: "Integrations with Gusto, ADP, Deel, BambooHR, Okta, Azure AD." },
    ],
    benefits: [
      "Faster onboarding with templated workflows",
      "Higher policy compliance via tracked approvals",
      "Cleaner audits with versioned documents",
      "Better engagement with structured feedback",
    ],
    useCases: [
      "Mid-market companies replacing spreadsheets",
      "Multi-country distributed teams",
      "Regulated industries needing audit trails",
      "Companies with complex leave/policy rules",
    ],
    techStack: ["Next.js", "PostgreSQL", "Auth0 / Okta", "DocuSign", "Gusto / ADP APIs", "AWS"],
    process: [
      { step: "Discovery", description: "Org model, policies, compliance, integrations." },
      { step: "Design", description: "Employee, manager, and admin experiences." },
      { step: "Build", description: "Modules, integrations, automations." },
      { step: "Roll out", description: "Migration, training, change management." },
    ],
    timeline: "12 – 20 weeks",
    deliverables: ["HR platform", "Employee + manager apps", "Integrations", "Reporting"],
  },
  {
    slug: "erp-integration",
    category: "web-development",
    title: "ERP & Legacy System Web Integration",
    subtitle: "Modern web on top of legacy systems",
    tagline: "Web layers, APIs, and integrations that bring legacy systems online — safely.",
    description:
      "Surface ERP and legacy data on modern web apps, with clean APIs, sync engines, and migration paths.",
    image:
      "https://images.unsplash.com/photo-1573164713619-24c711fe7878?w=1600&q=80&auto=format&fit=crop",
    icon: "Network",
    overview:
      "Most enterprises run on systems they can't replace. We build the modern web layer on top: secure APIs, sync engines, and user-friendly interfaces that put ERP data in the hands of teams, partners, and customers — without breaking the legacy core.",
    features: [
      { title: "API & middleware layer", description: "Clean REST/GraphQL APIs over legacy databases, mainframes, and ERPs." },
      { title: "Sync engines", description: "Change-data-capture, queues, retries, and conflict resolution." },
      { title: "Read replicas & caching", description: "Protect legacy systems with read-side caches and projections." },
      { title: "Modern UI on legacy data", description: "Customer portals, partner portals, internal tools." },
      { title: "Identity bridging", description: "SSO between legacy and modern systems." },
      { title: "Migration paths", description: "Strangler-fig pattern for gradual modernisation." },
    ],
    benefits: [
      "Lower risk than a full rip-and-replace",
      "Faster value delivery to users",
      "Reduced load on legacy systems",
      "Foundation for incremental modernisation",
    ],
    useCases: [
      "SAP / Oracle / Dynamics integration",
      "AS/400 & mainframe modernisation",
      "Multi-system data unification",
      "Acquisition-driven IT consolidation",
    ],
    techStack: ["Next.js", "Node.js / Python", "Kafka / RabbitMQ", "Redis", "Postgres", "Docker / Kubernetes"],
    process: [
      { step: "System audit", description: "Map data flows, dependencies, and risks." },
      { step: "Integration design", description: "API contracts, sync patterns, observability." },
      { step: "Build", description: "Middleware, web apps, monitoring." },
      { step: "Operate", description: "Gradual cutover, support, and continued modernisation." },
    ],
    timeline: "16 – 24+ weeks",
    deliverables: ["Integration middleware", "Web apps", "Monitoring & alerting", "Documentation"],
  },
  {
    slug: "iot-dashboard",
    category: "web-development",
    title: "Real-Time Operations & IoT Dashboard",
    subtitle: "Live data, control, and alerts",
    tagline: "Operations command centres for live data, devices, and alerting.",
    description:
      "Real-time dashboards for IoT fleets, factory floors, logistics, and operations centres.",
    image:
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1600&q=80&auto=format&fit=crop",
    icon: "Activity",
    overview:
      "When milliseconds matter, polling dashboards don't cut it. We build true real-time operations centres — WebSocket-streamed telemetry, device control, smart alerting, and historical analytics — designed to live on a wall display or a control-room screen.",
    features: [
      { title: "Streaming telemetry", description: "WebSocket / MQTT pipelines for sub-second updates." },
      { title: "Device control", description: "Two-way commands with audit trails and safety checks." },
      { title: "Smart alerting", description: "Threshold, trend, and anomaly alerts to Slack, SMS, PagerDuty." },
      { title: "Map & floorplan views", description: "Geo & spatial visualisation for fleets and facilities." },
      { title: "Time-series analytics", description: "Historical charts, downsampling, and export." },
      { title: "Role-based control", description: "Operators, supervisors, and auditors with scoped access." },
    ],
    benefits: [
      "Faster incident response from live alerts",
      "Reduced downtime via predictive insight",
      "Single pane of glass for operations",
      "Tighter compliance via audit trails",
    ],
    useCases: [
      "Manufacturing OEE & MES dashboards",
      "Logistics & fleet command centres",
      "Smart-building & energy dashboards",
      "Connected device fleets (IoT)",
    ],
    techStack: ["Next.js", "WebSockets / MQTT", "InfluxDB / TimescaleDB", "Grafana", "AWS IoT / Azure IoT", "Mapbox"],
    process: [
      { step: "Data pipeline", description: "Devices, brokers, schemas, retention." },
      { step: "Dashboard UX", description: "Layouts, role-based views, alert flows." },
      { step: "Build", description: "Streaming UI, alerting, analytics." },
      { step: "Operate", description: "Pilot, tune thresholds, and scale." },
    ],
    timeline: "12 – 20 weeks",
    deliverables: ["Real-time dashboard", "Alerting", "Device control", "Analytics"],
  },

  // ───────────── AI & AUTOMATION ─────────────
  {
    slug: "ai-chatbot",
    category: "ai-automation",
    title: "AI Chatbot & Virtual Assistant",
    subtitle: "Always-on, brand-aware conversation",
    tagline: "Conversational AI trained on your business — built to answer, qualify, and convert.",
    description:
      "Custom AI chatbots that handle inquiries, qualify leads, book meetings, and hand off to humans when it matters.",
    image: "/ai-automation-images/ai-chatbot.png",
    icon: "MessageSquare",
    overview:
      "Generic chatbot templates fail because they don't know your products, your tone, or your edge cases. We build AI assistants grounded in your knowledge base, fine-tuned to your voice, and integrated with your tools — so they actually help users, not annoy them.",
    features: [
      { title: "Brand & product grounding", description: "RAG over your docs, FAQs, product catalogue, and support history." },
      { title: "Multi-channel deployment", description: "Web widget, WhatsApp, Messenger, Slack, Teams, voice." },
      { title: "Human handover", description: "Smart escalation with conversation context to your CRM/helpdesk." },
      { title: "Actions & tool use", description: "Book meetings, create tickets, look up orders, update CRM." },
      { title: "Multilingual", description: "Auto-detect and respond in 50+ languages." },
      { title: "Analytics & guardrails", description: "Quality monitoring, prompt observability, and PII redaction." },
    ],
    benefits: [
      "24/7 coverage with consistent quality",
      "Higher conversion from instant responses",
      "Lower support cost per interaction",
      "Better lead capture during off-hours",
    ],
    useCases: [
      "B2B SaaS sales-assist chatbot",
      "eCommerce product advisor",
      "Internal knowledge copilot",
      "WhatsApp/voice customer service",
    ],
    techStack: ["OpenAI / Anthropic", "LangChain / LangGraph", "Pinecone / Weaviate", "Next.js", "Twilio", "Zendesk / HubSpot"],
    process: [
      { step: "Scope & data", description: "Map intents, knowledge sources, and success metrics." },
      { step: "Knowledge prep", description: "Ingest, chunk, embed, and evaluate retrieval." },
      { step: "Build & integrate", description: "Conversation flows, actions, handover, UI." },
      { step: "Evaluate & tune", description: "Eval set, online monitoring, prompt iteration." },
    ],
    timeline: "4 – 10 weeks",
    deliverables: ["Bot + channels", "Knowledge pipeline", "CRM/helpdesk integration", "Eval dashboard"],
  },
  {
    slug: "ai-lead-qualification",
    category: "ai-automation",
    title: "AI Lead Qualification & CRM Automation",
    subtitle: "Score, enrich, route, follow up",
    tagline: "Stop your reps from working junk leads — AI sorts the pipeline before they wake up.",
    description:
      "Automated lead scoring, enrichment, routing, and follow-up sequences powered by AI.",
    image: "/ai-automation-images/ai-lead-qualification.png",
    icon: "Filter",
    overview:
      "Sales teams burn hours on leads that were never going to close. We build AI pipelines that ingest leads from every source, enrich them with firmographic and intent data, score them with your historical CRM signals, route them to the right rep, and trigger personalised first-touch sequences — automatically.",
    features: [
      { title: "Multi-source ingestion", description: "Forms, ads, list uploads, webinar tools, intent platforms." },
      { title: "AI enrichment", description: "Firmographic, technographic, role, and intent signals." },
      { title: "Predictive scoring", description: "Model trained on your won/lost history, not a generic template." },
      { title: "Smart routing", description: "Territory, vertical, deal size, language — assign to the right rep." },
      { title: "Personalised outreach", description: "AI-drafted first emails tuned to lead context and ICP." },
      { title: "Closed-loop learning", description: "Score refines as new deals close." },
    ],
    benefits: [
      "Higher rep productivity — less time on bad leads",
      "Faster speed-to-lead with auto first-touch",
      "Better forecast accuracy from real scoring",
      "Cleaner CRM hygiene through automated enrichment",
    ],
    useCases: [
      "Outbound SDR teams",
      "Inbound marketing funnels",
      "Event & webinar follow-up",
      "Account-based selling motions",
    ],
    techStack: ["HubSpot / Salesforce / Pipedrive", "Clay / Apollo / Clearbit", "OpenAI", "Make / n8n / Zapier", "PostgreSQL"],
    process: [
      { step: "Audit", description: "Map sources, CRM model, and ideal customer." },
      { step: "Model design", description: "Scoring features, enrichment vendors, routing rules." },
      { step: "Build", description: "Pipelines, scoring, sequences, dashboards." },
      { step: "Operate", description: "A/B test, monitor, retrain." },
    ],
    timeline: "4 – 10 weeks",
    deliverables: ["Enrichment pipeline", "Scoring model", "Routing & sequences", "Sales dashboard"],
  },
  {
    slug: "ai-customer-support",
    category: "ai-automation",
    title: "AI Customer Support Bot",
    subtitle: "Resolve, deflect, escalate",
    tagline: "AI support agents that resolve tickets, not just route them.",
    description:
      "AI-powered support agents that handle Tier-1 tickets, draft Tier-2 replies, and escalate cleanly.",
    image:
      "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=1600&q=80&auto=format&fit=crop",
    icon: "Headphones",
    overview:
      "Modern AI support isn't a chatbot bolted onto your helpdesk — it's an agent that can read tickets, search history, pull data from your systems, and either resolve or hand off with a fully drafted response. We build both: customer-facing deflection and agent-facing copilots.",
    features: [
      { title: "Ticket understanding", description: "Classify intent, urgency, sentiment, and required actions." },
      { title: "Knowledge retrieval", description: "Search docs, past tickets, code, and product data in one query." },
      { title: "Action execution", description: "Refunds, account changes, order lookups — with policy guardrails." },
      { title: "Agent copilot", description: "Drafted responses, summaries, and next-best-action for human agents." },
      { title: "Quality monitoring", description: "Eval against gold tickets, hallucination detection, audit trail." },
      { title: "Helpdesk-native", description: "Zendesk, Intercom, Freshdesk, HubSpot Service, Salesforce." },
    ],
    benefits: [
      "30 – 60% deflection on common tickets",
      "Faster average handle time for human agents",
      "Higher CSAT from instant, accurate replies",
      "Reduced burnout from repetitive work",
    ],
    useCases: [
      "eCommerce order & returns support",
      "SaaS Tier-1 technical support",
      "Telco & utilities self-service",
      "Travel & hospitality customer service",
    ],
    techStack: ["OpenAI / Anthropic", "LangGraph", "Pinecone / Weaviate", "Zendesk / Intercom APIs", "PostgreSQL", "Sentry"],
    process: [
      { step: "Ticket audit", description: "Top intents, deflection candidates, eval set." },
      { step: "Agent design", description: "Tools, policies, escalation rules." },
      { step: "Build", description: "Agent, copilot UI, integrations." },
      { step: "Pilot & scale", description: "Shadow mode, gradual rollout, retraining." },
    ],
    timeline: "6 – 12 weeks",
    deliverables: ["Support agent", "Agent copilot", "Helpdesk integration", "Quality dashboards"],
  },
  {
    slug: "ai-document-processing",
    category: "ai-automation",
    title: "AI Document Processing & Data Extraction",
    subtitle: "Invoices, contracts, IDs, forms — at scale",
    tagline: "Turn unstructured documents into clean, validated data — automatically.",
    description:
      "AI pipelines for OCR, classification, extraction, and validation across high-volume document workflows.",
    image:
      "https://images.unsplash.com/photo-1568667256549-094345857637?w=1600&q=80&auto=format&fit=crop",
    icon: "FileScan",
    overview:
      "Document processing is one of the highest-ROI AI use cases: every hour spent typing data into a system is an hour not spent on something strategic. We build extraction pipelines that handle messy real-world documents — invoices, contracts, IDs, claims, statements — with confidence scoring and human-in-the-loop review.",
    features: [
      { title: "Multi-format ingestion", description: "PDF, scans, photos, emails, faxes — single or batch." },
      { title: "Document classification", description: "Sort incoming docs by type, vendor, customer, or use case." },
      { title: "Structured extraction", description: "Line-items, totals, dates, signatures, and custom fields." },
      { title: "Validation & rules", description: "Schema validation, business rules, three-way match for AP." },
      { title: "Human-in-the-loop", description: "Review queues for low-confidence items with active learning." },
      { title: "System sync", description: "Push clean data to ERP, accounting, CRM, or data warehouse." },
    ],
    benefits: [
      "70 – 95% reduction in manual data entry",
      "Faster cycle times for AP, claims, or onboarding",
      "Lower error rates with validation rules",
      "Full audit trail for compliance",
    ],
    useCases: [
      "AP automation (invoices, POs, receipts)",
      "Contract data extraction",
      "Insurance claims & forms",
      "KYC / onboarding documents",
    ],
    techStack: ["GPT-4o / Claude Vision", "Azure / AWS OCR", "Python", "Temporal", "PostgreSQL", "Snowflake / BigQuery"],
    process: [
      { step: "Document audit", description: "Sample real docs, define fields, build eval set." },
      { step: "Pipeline design", description: "OCR, models, validation, routing." },
      { step: "Build & integrate", description: "Pipelines, review UI, downstream sync." },
      { step: "Operate", description: "Monitor accuracy, retrain, expand scope." },
    ],
    timeline: "6 – 14 weeks",
    deliverables: ["Extraction pipeline", "Review UI", "Integrations", "Accuracy dashboard"],
  },
  {
    slug: "workflow-automation",
    category: "ai-automation",
    title: "Business Process & Workflow Automation",
    subtitle: "Wire systems, eliminate handoffs",
    tagline: "Replace email-ping-pong and copy-paste work with reliable, auditable automations.",
    description:
      "Workflow automation that connects your tools, removes manual steps, and surfaces exceptions.",
    image:
      "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=1600&q=80&auto=format&fit=crop",
    icon: "Workflow",
    overview:
      "Every team has workflows that span 4 – 6 systems and rely on humans to copy data between them. We map those flows, replace them with reliable automations (Temporal, n8n, custom code, or AI agents where it helps), and give you observability into what ran, what failed, and why.",
    features: [
      { title: "Process discovery", description: "Map current state, identify hand-off pain points and metrics." },
      { title: "Reliable orchestration", description: "Retries, idempotency, durable execution — not just no-code glue." },
      { title: "AI-enabled steps", description: "Drop AI into the steps that need judgment: classification, drafting, summarisation." },
      { title: "Approvals & humans", description: "In-the-loop approvals via Slack, email, or web." },
      { title: "Observability", description: "Audit log, retries, SLAs, and alerts." },
      { title: "Cross-stack", description: "Salesforce, NetSuite, Slack, Notion, Google, AWS, custom APIs." },
    ],
    benefits: [
      "Lower operational cost per transaction",
      "Faster cycle times across departments",
      "Fewer errors from manual copy-paste",
      "Clear audit trail for finance / compliance",
    ],
    useCases: [
      "Order-to-cash automation",
      "Procure-to-pay & vendor onboarding",
      "Employee onboarding / offboarding",
      "Marketing-to-sales handoff",
    ],
    techStack: ["Temporal", "n8n", "Python / TypeScript", "OpenAI", "Slack / Teams", "PostgreSQL"],
    process: [
      { step: "Map", description: "Current process, systems, owners, metrics." },
      { step: "Design", description: "Future state with automations and humans-in-the-loop." },
      { step: "Build", description: "Workflows, integrations, observability." },
      { step: "Operate", description: "Monitor, refine, expand to next process." },
    ],
    timeline: "4 – 12 weeks",
    deliverables: ["Workflow library", "Dashboards & alerts", "Documentation", "Training"],
  },
  {
    slug: "ai-inventory-forecasting",
    category: "ai-automation",
    title: "AI-Powered Inventory & Demand Forecasting",
    subtitle: "Less stockout, less overstock",
    tagline: "Forecasts that beat your spreadsheets — and explain themselves.",
    description:
      "Demand forecasting and replenishment optimisation powered by machine learning.",
    image:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1600&q=80&auto=format&fit=crop",
    icon: "TrendingUp",
    overview:
      "Spreadsheet-based forecasting can't see the patterns hiding in your data: seasonality, weather, promotions, cannibalisation, lead-time variability. We build forecasting systems that feed your replenishment with better numbers — and surface their reasoning so your planners trust them.",
    features: [
      { title: "Demand forecasting", description: "Per-SKU per-location forecasts with confidence intervals." },
      { title: "Causal features", description: "Promotions, weather, holidays, pricing, and competitor signals." },
      { title: "Replenishment optimisation", description: "Reorder points, safety stock, and PO recommendations." },
      { title: "Scenario planning", description: "What-if analysis for promos, launches, and supply disruptions." },
      { title: "Explanations", description: "Top drivers per forecast so planners can sanity-check." },
      { title: "ERP & WMS sync", description: "Push recommendations into your operational systems." },
    ],
    benefits: [
      "Lower carrying cost from reduced overstock",
      "Higher service levels via better safety stock",
      "Faster planner cycles with auto-recommendations",
      "Better promo planning through scenario tools",
    ],
    useCases: [
      "Retail & DTC replenishment",
      "Wholesale distribution",
      "Manufacturing raw-material planning",
      "QSR ingredient forecasting",
    ],
    techStack: ["Python", "Prophet / Nixtla / DeepAR", "Snowflake / BigQuery", "dbt", "Next.js", "Airflow / Dagster"],
    process: [
      { step: "Data audit", description: "Sales history, master data, exogenous signals." },
      { step: "Model build", description: "Baselines, ML models, evaluation harness." },
      { step: "Productionise", description: "Pipelines, UI, recommendation engine." },
      { step: "Iterate", description: "Monitor accuracy, retrain, expand scope." },
    ],
    timeline: "8 – 16 weeks",
    deliverables: ["Forecast engine", "Planner UI", "ERP/WMS integration", "Model monitoring"],
  },
  {
    slug: "executive-reporting",
    category: "ai-automation",
    title: "Automated Executive Reporting & AI Insights",
    subtitle: "Board-ready, every Monday morning",
    tagline: "Stop building decks. Get narratives, charts, and what-changed-and-why on a schedule.",
    description:
      "Automated executive reporting that combines BI data with AI-generated narrative and recommendations.",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&q=80&auto=format&fit=crop",
    icon: "BarChart3",
    overview:
      "Executives don't need more dashboards — they need explanations. We build reporting systems that pull data from your stack, run anomaly detection, and generate a narrative summary that reads like a competent analyst wrote it. Delivered to inbox, Slack, or the boardroom screen.",
    features: [
      { title: "Cross-source data", description: "Pull KPIs from your warehouse, CRM, ad platforms, finance, ops." },
      { title: "AI-generated narrative", description: "Plain-language summary of what changed and why." },
      { title: "Anomaly detection", description: "Flag spikes, drops, and trend breaks automatically." },
      { title: "Scheduled delivery", description: "Email, Slack, PDF, or board-deck format on cadence." },
      { title: "Drill-down", description: "Click any number to see the underlying breakdown." },
      { title: "Custom commentary", description: "Add finance-team notes that the AI weaves in." },
    ],
    benefits: [
      "Hours saved every reporting cycle",
      "Consistent narrative quality across stakeholders",
      "Faster reactions to anomalies",
      "Decks that arrive even when the analyst is on PTO",
    ],
    useCases: [
      "Weekly leadership business reviews",
      "Monthly board reports",
      "Quarterly investor updates",
      "Daily ops snapshots",
    ],
    techStack: ["Snowflake / BigQuery", "dbt", "OpenAI / Claude", "Next.js", "Slack / SendGrid", "Metabase / Looker"],
    process: [
      { step: "KPI agreement", description: "Define audience, metrics, and tone." },
      { step: "Data plumbing", description: "Sources, models, semantic layer." },
      { step: "Generator", description: "Prompt design, eval, and templating." },
      { step: "Deliver", description: "Channels, scheduling, and feedback loop." },
    ],
    timeline: "6 – 12 weeks",
    deliverables: ["Reporting engine", "Templates", "Delivery channels", "Eval / guardrails"],
  },
  {
    slug: "predictive-analytics",
    category: "ai-automation",
    title: "Predictive Analytics & Business Intelligence",
    subtitle: "From dashboards to decisions",
    tagline: "BI that doesn't just show the past — it predicts the next quarter.",
    description:
      "End-to-end analytics: warehouse, modelling, dashboards, and predictive models that drive decisions.",
    image: "/ai-automation-images/predictive-analytics.png",
    icon: "LineChart",
    overview:
      "Most BI projects stall because the data isn't ready or the dashboards never answer the question. We build pragmatic analytics stacks: clean data warehouse, a tested semantic layer, dashboards your team actually uses, and predictive models layered on top — churn, LTV, upsell, demand, fraud.",
    features: [
      { title: "Modern data stack", description: "Warehouse, ELT, dbt models, semantic layer." },
      { title: "Self-serve dashboards", description: "Metabase, Looker, Hex, or custom — versioned and governed." },
      { title: "Predictive models", description: "Churn, LTV, conversion, fraud, demand — productionised and monitored." },
      { title: "Experimentation", description: "A/B framework with statistical rigour." },
      { title: "Reverse ETL", description: "Push insights back into CRM, ad platforms, and product." },
      { title: "Data quality", description: "Tests, freshness checks, and incident workflows." },
    ],
    benefits: [
      "Decisions backed by trusted, fresh data",
      "Higher conversion from targeted predictions",
      "Lower churn via early-warning models",
      "Faster experimentation cycles",
    ],
    useCases: [
      "B2B SaaS revenue analytics",
      "eCommerce growth & retention",
      "Marketplace dynamics",
      "Operations & supply chain analytics",
    ],
    techStack: ["Snowflake / BigQuery", "dbt", "Fivetran / Airbyte", "Python (scikit-learn / XGBoost)", "Hex / Metabase", "Hightouch"],
    process: [
      { step: "Assess", description: "Sources, current dashboards, decision gaps." },
      { step: "Architect", description: "Warehouse, models, governance." },
      { step: "Build", description: "Pipelines, dashboards, predictive models." },
      { step: "Activate", description: "Reverse-ETL, experiments, ongoing analytics." },
    ],
    timeline: "10 – 20 weeks",
    deliverables: ["Data warehouse", "Dashboard suite", "Predictive models", "Reverse-ETL"],
  },
  {
    slug: "ai-hr-recruitment",
    category: "ai-automation",
    title: "AI-Powered HR & Recruitment Automation",
    subtitle: "Screen, schedule, and engage at scale",
    tagline: "AI handles the funnel volume so recruiters can do the work that matters.",
    description:
      "AI-driven candidate screening, scheduling, sourcing, and onboarding automations.",
    image:
      "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1600&q=80&auto=format&fit=crop",
    icon: "UserCheck",
    overview:
      "Recruiting teams drown in resumes and emails. We build AI workflows that screen and rank candidates against your real success criteria, auto-schedule interviews, draft sourcing outreach, and run onboarding checklists — all while keeping a human in every consequential decision.",
    features: [
      { title: "Smart screening", description: "Match resumes to roles using semantic similarity, not keywords." },
      { title: "Sourcing assist", description: "Draft personalised outreach to passive candidates at scale." },
      { title: "Auto-scheduling", description: "Interview coordination across panels, time zones, and tools." },
      { title: "Structured interviews", description: "AI-generated, role-specific question banks and rubrics." },
      { title: "Onboarding automations", description: "Day-one tasks, equipment, accounts, and training." },
      { title: "ATS-native", description: "Integrates with Greenhouse, Lever, Workday, BambooHR." },
    ],
    benefits: [
      "Faster time-to-hire",
      "Better quality-of-hire with structured rubrics",
      "Higher candidate satisfaction from responsive flows",
      "Recruiters focused on relationships, not logistics",
    ],
    useCases: [
      "High-volume hiring (retail, BPO, support)",
      "Tech recruiting with structured interviewing",
      "Executive search outreach",
      "Internal mobility & onboarding",
    ],
    techStack: ["OpenAI", "Greenhouse / Lever / Workday", "Calendly / Cronofy", "Next.js", "Slack", "PostgreSQL"],
    process: [
      { step: "Audit", description: "Funnel metrics, bottlenecks, fairness considerations." },
      { step: "Design", description: "Workflows, eval criteria, human checkpoints." },
      { step: "Build", description: "Automations, dashboards, integrations." },
      { step: "Operate", description: "Monitor outcomes, fairness, and adjust." },
    ],
    timeline: "6 – 12 weeks",
    deliverables: ["Screening & sourcing automations", "Scheduling", "Onboarding workflows", "Dashboards"],
  },
  {
    slug: "custom-ai-agent",
    category: "ai-automation",
    title: "Custom AI Agent Development",
    subtitle: "Purpose-built agents for your operations",
    tagline: "Agents that plan, act, and check their own work — built around your tools and policies.",
    description:
      "Custom agentic systems for research, operations, sales, and engineering — with the right guardrails.",
    image:
      "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1600&q=80&auto=format&fit=crop",
    icon: "Bot",
    overview:
      "A real agent isn't a chatbot — it's a system that decomposes goals, calls tools, evaluates progress, and recovers from errors. We build agents that work inside your stack: research, sales operations, engineering co-pilots, ops triage, document workflows. Production-ready, observable, and safe.",
    features: [
      { title: "Tool & API access", description: "Custom toolkits for your CRM, data, codebase, and internal services." },
      { title: "Planning & memory", description: "Goal decomposition, durable memory, and self-evaluation." },
      { title: "Guardrails", description: "Allow-lists, rate limits, action approvals, and PII filters." },
      { title: "Human handover", description: "Escalation when confidence drops or stakes are high." },
      { title: "Observability", description: "Full trace of every step, decision, and tool call." },
      { title: "Continuous evals", description: "Offline eval set + online quality monitoring." },
    ],
    benefits: [
      "Step-change productivity on agent-friendly tasks",
      "Faster operations with 24/7 coverage",
      "Compliant by design with guardrails and audit",
      "Compounding ROI as capabilities expand",
    ],
    useCases: [
      "Research / due-diligence agents",
      "Sales-ops & RevOps agents",
      "Engineering co-pilots on private codebases",
      "Operations triage & runbook agents",
    ],
    techStack: ["LangGraph / Mastra", "OpenAI / Anthropic", "Pinecone / Weaviate", "Temporal", "Next.js", "OpenTelemetry"],
    process: [
      { step: "Use-case design", description: "Pick a task with clear input, output, and metric." },
      { step: "Toolkit & data", description: "Tools, data access, guardrails, eval set." },
      { step: "Build & evaluate", description: "Agent, traces, evals, human-in-the-loop." },
      { step: "Deploy & expand", description: "Production rollout, monitoring, capability growth." },
    ],
    timeline: "6 – 16 weeks",
    deliverables: ["Production agent", "Tool integrations", "Observability", "Eval harness"],
  },
];

export const getServiceBySlug = (slug) =>
  SERVICES.find((s) => s.slug === slug);

export const getServicesByCategory = (categorySlug) =>
  SERVICES.filter((s) => s.category === categorySlug);

export const ALL_SERVICE_SLUGS = SERVICES.map((s) => s.slug);
